conn_all_query = ('insert into conn_all(app_category,app_id,app_name,app_proto,conn_uuid,dst_dir,dst_direction,dst_hostname,dst_nbytes,dst_npackets,dst_pbytes,dst_username,encryption,end_time,input,ip_dst_port,ip_dst_saddr,ip_src_port,ip_src_saddr,output,src_dir,src_direction,src_hostname,src_nbytes,src_npackets,src_pbytes,src_username,start_time,tags,transport_proto,vlanid,policy,policyid,cloud_policyid,src_hwaddr,dst_hwaddr,interface,is_blocked,is_local,security_tags,security_tags_len,src_country_name,dst_country_name,dst_geoip_lat,dst_geoip_lon,device_id,device_name,device_category,device_vendor,device_os,device_osver)' 
                  ' values(:app_category,:app_id,:app_name,:app_proto,:conn_uuid,:dst_dir,:dst_direction,:dst_hostname,:dst_nbytes,:dst_npackets,:dst_pbytes,:dst_username,:encryption,:end_time,:input,:ip_dst_port,:ip_dst_saddr,:ip_src_port,:ip_src_saddr,:output,:src_dir,:src_direction,:src_hostname,:src_nbytes,:src_npackets,:src_pbytes,:src_username,:start_time,:tags,:transport_proto,:vlanid,:policy,:policyid,:cloud_policyid,:src_hwaddr, :dst_hwaddr,:interface,:is_blocked,:is_local,:security_tags,:security_tags_len,:src_country_name,:dst_country_name,:dst_geoip_lat,:dst_geoip_lon,:device_id,:device_name, :device_category, :device_vendor, :device_os, :device_osver)')
conn_all_parameter = {'app_category': '','app_id': '','app_name': '','app_proto': '','conn_uuid': '','dst_dir': '','dst_direction': '','dst_hostname': '','dst_nbytes': '','dst_npackets': '','dst_pbytes': '','dst_username': '','encryption': '','end_time': '','input': '','ip_dst_port': '','ip_dst_saddr': '','ip_src_port': '','ip_src_saddr': '','output': '','src_dir': '','src_direction': '','src_hostname': '','src_nbytes': '','src_npackets': '','src_pbytes': '','src_username': '','start_time': 0,'tags': '','transport_proto': '','vlanid': '','policy': '','policyid': '','cloud_policyid':'','src_hwaddr':'','dst_hwaddr':'','interface': '','is_blocked': '','is_local': '','security_tags_len':0 ,'security_tags': '','src_country_name':'','dst_country_name':'','dst_geoip_lat':0,'dst_geoip_lon':0,'device_id': '','device_name': '','device_category': '','device_vendor': '','device_os': '','device_osver': ''}

http_all_query = ('insert into http_all(browser,category,cli_hdr_names,conn_uuid,cookie_vars,deviceversion,dst_hostname,encryption,host,ip_dst_port,ip_dst_saddr,ip_src_port,ip_src_saddr,method,os,osversion,proto,proxied,referrer,req_body_len,rsp_body_len,src_hostname,srv_hdr_names,start_time,status_msg,transport_proto,uri,uri_vars,user_agent,version,vlanid,policy,policyid,cloud_policyid,src_hwaddr,dst_hwaddr,interface,dst_username,src_username,is_blocked,is_local,src_country_name,dst_country_name,src_dir,device_id,device_name,device_category,device_vendor,device_os,device_osver)' 
                  ' values(:browser,:category,:cli_hdr_names,:conn_uuid,:cookie_vars,:deviceversion,:dst_hostname,:encryption,:host,:ip_dst_port,:ip_dst_saddr,:ip_src_port,:ip_src_saddr,:method,:os,:osversion,:proto,:proxied,:referrer,:req_body_len,:rsp_body_len,:src_hostname,:srv_hdr_names,:start_time,:status_msg,:transport_proto,:uri,:uri_vars,:user_agent,:version,:vlanid,:policy,:policyid,:cloud_policyid,:src_hwaddr, :dst_hwaddr,:interface,:dst_username,:src_username,:is_blocked,:is_local,:src_country_name,:dst_country_name,:src_dir,:device_id,:device_name, :device_category, :device_vendor, :device_os, :device_osver)')
http_all_parameter = {'browser': '','category': '','cli_hdr_names': '','conn_uuid': '','cookie_vars': '','deviceversion': '','dst_hostname': '','encryption': '','host': '','ip_dst_port': '','ip_dst_saddr': '','ip_src_port': '','ip_src_saddr': '','method': '','os': '','osversion': '','proto': '','proxied': '','referrer': '','req_body_len': '','rsp_body_len': '','src_hostname': '','srv_hdr_names': '','start_time': '','status_msg': '','transport_proto': '','uri': '','uri_vars': '','user_agent': '','version': '','vlanid': '','policy': '','policyid': '','cloud_policyid':'','src_hwaddr':'','dst_hwaddr':'','interface': '','dst_username': '','src_username': '','is_blocked': '','is_local': '','src_country_name':'','dst_country_name':'','src_dir':'','device_id': '','device_name': '','device_category': '','device_vendor': '','device_os': '','device_osver': ''}

alert_all_query = ('insert into alert_all(alertinfo_action,alertinfo_category,alertinfo_gid,alertinfo_rev,alertinfo_severity,alertinfo_sid,alertinfo_signature,app_proto,conn_uuid,dst_hostname,in_iface,ip_dst_port,ip_dst_saddr,ip_src_port,ip_src_saddr,message,src_hostname,start_time,tags,transport_proto,vlanid,policy,policyid,cloud_policyid,src_hwaddr,dst_hwaddr,interface,dst_username,src_username,is_blocked,is_local,src_country_name,dst_country_name,src_dir,device_id,device_name,device_category,device_vendor,device_os,device_osver)' 
                  ' values(:alertinfo_action,:alertinfo_category,:alertinfo_gid,:alertinfo_rev,:alertinfo_severity,:alertinfo_sid,:alertinfo_signature,:app_proto,:conn_uuid,:dst_hostname,:in_iface,:ip_dst_port,:ip_dst_saddr,:ip_src_port,:ip_src_saddr,:message,:src_hostname,:start_time,:tags,:transport_proto,:vlanid,:policy,:policyid,:cloud_policyid,:src_hwaddr, :dst_hwaddr,:interface,:dst_username,:src_username,:is_blocked,:is_local,:src_country_name,:dst_country_name,:src_dir,:device_id,:device_name, :device_category, :device_vendor, :device_os, :device_osver)')
alert_all_parameter = {'alertinfo_action': '','alertinfo_category': '','alertinfo_gid': '','alertinfo_rev': '','alertinfo_severity': '','alertinfo_sid': '','alertinfo_signature': '','app_proto': '','conn_uuid': '','dst_hostname': '','in_iface': '','ip_dst_port': '','ip_dst_saddr': '','ip_src_port': '','ip_src_saddr': '','message': '','src_hostname': '','start_time': '','tags': '','transport_proto': '','vlanid': '','policy': '','policyid': '','cloud_policyid':'','src_hwaddr':'','dst_hwaddr':'','interface': '','dst_username': '','src_username': '','is_blocked': '','is_local': '','src_country_name':'','dst_country_name':'','src_dir':'','device_id': '','device_name': '','device_category': '','device_vendor': '','device_os': '','device_osver': ''}

dns_all_query = ('insert into dns_all(answers,conn_uuid,encryption,ip_dst_port,ip_dst_saddr,ip_src_port,ip_src_saddr,is_AA,is_RA,is_RD,is_TC,is_request,is_response,proto,qclass,qtype,query,resp_code,start_time,total_answers,trans_id,vlanid,policy,policyid,cloud_policyid,src_hwaddr,dst_hwaddr,interface,dst_username,src_username,is_blocked,is_local,src_country_name,dst_country_name,src_dir,src_hostname,dst_hostname,ttls,device_id,device_name,device_category,device_vendor,device_os,device_osver)' 
                  ' values(:answers,:conn_uuid,:encryption,:ip_dst_port,:ip_dst_saddr,:ip_src_port,:ip_src_saddr,:is_AA,:is_RA,:is_RD,:is_TC,:is_request,:is_response,:proto,:qclass,:qtype,:query,:resp_code,:start_time,:total_answers,:trans_id,:vlanid,:policy,:policyid,:cloud_policyid,:src_hwaddr, :dst_hwaddr,:interface,:dst_username,:src_username,:is_blocked,:is_local,:src_country_name,:dst_country_name,:src_dir,:src_hostname,:dst_hostname,:ttls,:device_id,:device_name, :device_category, :device_vendor, :device_os, :device_osver)')
dns_all_parameter = {'answers': '','conn_uuid': '','encryption': '','ip_dst_port': '','ip_dst_saddr': '','ip_src_port': '','ip_src_saddr': '','is_AA': '','is_RA': '','is_RD': '','is_TC': '','is_request': '','is_response': '','proto': '','qclass': '','qtype': '','query': '','resp_code': '','start_time': '','total_answers': '','trans_id': '','vlanid': '','policy': '','policyid': '','cloud_policyid':'','src_hwaddr':'','dst_hwaddr':'','interface': '','dst_username': '','src_username': '','is_blocked': '','is_local': '','src_country_name':'','dst_country_name':'','src_dir':'','src_hostname':'','dst_hostname':'','ttls':'','device_id': '','device_name': '','device_category': '','device_vendor': '','device_os': '','device_osver': ''}

sip_all_query = ('insert into sip_all(call_id,encryption,from_ext,from_name,from_user,ip_dst_port,ip_dst_saddr,ip_src_port,ip_src_saddr,method,proto,referrer,start_time,status,status_msg,to_ext,to_name,to_user,user_agent,vlanid,policy,policyid,cloud_policyid,src_hwaddr,dst_hwaddr,interface,dst_username,src_username,is_blocked,is_local,device_id,device_name,device_category,device_vendor,device_os,device_osver)' 
                  ' values(,:call_id,:encryption,:from_ext,:from_name,:from_user,:ip_dst_port,:ip_dst_saddr,:ip_src_port,:ip_src_saddr,:method,:proto,:referrer,:start_time,:status,:status_msg,:to_ext,:to_name,:to_user,:user_agent,:vlanid,:policy,:policyid,:cloud_policyid,:src_hwaddr, :dst_hwaddr,:interface,:dst_username,:src_username,:is_blocked,:is_local,:device_id,:device_name, :device_category, :device_vendor, :device_os, :device_osver)')
sip_all_parameter = {'call_id': '','encryption': '','from_ext': '','from_name': '','from_user': '','ip_dst_port': '','ip_dst_saddr': '','ip_src_port': '','ip_src_saddr': '','method': '','proto': '','referrer': '','start_time': '','status': '','status_msg': '','to_ext': '','to_name': '','to_user': '','user_agent': '','vlanid': '','policy': '','policyid': '','cloud_policyid':'','src_hwaddr':'','dst_hwaddr':'','interface': '','dst_username': '','src_username': '','is_blocked': '','is_local': '','device_id': '','device_name': '','device_category': '','device_vendor': '','device_os': '','device_osver': ''}

tls_all_query = ('insert into tls_all(category,conn_uuid,dst_hostname,encryption,ip_dst_port,ip_dst_saddr,ip_src_port,ip_src_saddr,server_name,session_id,src_hostname,start_time,transport_proto,vlanid,policy,policyid,cloud_policyid,src_hwaddr,dst_hwaddr,interface,dst_username,src_username,is_blocked,is_local,src_country_name,dst_country_name,src_dir,device_id,device_name,device_category,device_vendor,device_os,device_osver)' 
                  ' values(:category,:conn_uuid,:dst_hostname,:encryption,:ip_dst_port,:ip_dst_saddr,:ip_src_port,:ip_src_saddr,:server_name,:session_id,:src_hostname,:start_time,:transport_proto,:vlanid,:policy,:policyid,:cloud_policyid,:src_hwaddr, :dst_hwaddr,:interface,:dst_username,:src_username,:is_blocked,:is_local,:src_country_name,:dst_country_name,:src_dir,:device_id,:device_name, :device_category, :device_vendor, :device_os, :device_osver)')
tls_all_parameter = {'category': '','conn_uuid': '','dst_hostname': '','encryption': '','ip_dst_port': '','ip_dst_saddr': '','ip_src_port': '','ip_src_saddr': '','server_name': '','session_id': '','src_hostname': '','start_time': '','transport_proto': '','vlanid': '','policy': '','policyid': '','cloud_policyid':'','src_hwaddr':'','dst_hwaddr':'','interface': '','dst_username': '','src_username': '','is_blocked': '','is_local': '','src_country_name':'','dst_country_name':'','src_dir':'','device_id': '','device_name': '','device_category': '','device_vendor': '','device_os': '','device_osver': ''}
