CREATE TABLE IF NOT EXISTS application_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE, uuid TEXT);
CREATE TABLE IF NOT EXISTS web_20_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS applications (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,description TEXT,web_20_category_id INTEGER,application_category_id INTEGER);
CREATE TABLE IF NOT EXISTS applications_last_id (id INTEGER default 0);
CREATE TABLE IF NOT EXISTS custom_applications (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,description TEXT,protocol TEXT default 'TCP',hostnames TEXT,ip_addrs TEXT,application_category_id INTEGER,port INTEGER);
CREATE TABLE IF NOT EXISTS custom_applications_host_ip (id INTEGER PRIMARY KEY AUTOINCREMENT,host TEXT,ip TEXT,custom_application_id integer);
CREATE TABLE IF NOT EXISTS policy_custom_app_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_id TEXT,custom_application_id INTEGER,uuid TEXT,action TEXT,writetofile TEXT);
CREATE TABLE IF NOT EXISTS web_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,is_security_category INTEGER);
CREATE TABLE IF NOT EXISTS policy_web_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_id TEXT,web_categories_id INTEGER,uuid TEXT,action TEXT);
CREATE TABLE IF NOT EXISTS policy_app_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_id TEXT,application_id INTEGER,uuid TEXT,action TEXT,writetofile TEXT);
CREATE TABLE IF NOT EXISTS policy_custom_web_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_id TEXT,custom_web_categories_id INTEGER);
CREATE TABLE IF NOT EXISTS custom_web_categories (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,uuid TEXT ,action TEXT);
CREATE TABLE IF NOT EXISTS custom_web_category_sites (id INTEGER PRIMARY KEY AUTOINCREMENT,custom_web_categories_id INTEGER,site TEXT,uuid TEXT,category_type TEXT default 'domain',is_global INTEGER default 0);
CREATE TABLE IF NOT EXISTS global_sites (id INTEGER PRIMARY KEY AUTOINCREMENT,site TEXT UNIQUE,uuid TEXT,site_type TEXT default 'domain',action TEXT default 'accept',status int default 1,policy_id INTEGER default 0);
CREATE TABLE IF NOT EXISTS policies (id INTEGER PRIMARY KEY,uuid text,name TEXT,usernames TEXT,groups TEXT,interfaces TEXT,vlans TEXT,networks TEXT,macaddresses TEXT,directions TEXT, delete_status INTEGER default 0,status INTEGER default 1,decision_is_block  INTEGER default 0,webcategory_type TEXT default 'permissive',sort_number integer default 0,cloud_id text,is_cloud integer default 0,is_centralized integer default 0,is_sync integer default 0,safe_search INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS schedules (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE ,mon_day INTEGER  DEFAULT 0,tue_day INTEGER  DEFAULT 0,wed_day INTEGER  DEFAULT 0,thu_day INTEGER  DEFAULT 0,fri_day INTEGER  DEFAULT 0,sat_day INTEGER  DEFAULT 0,sun_day INTEGER  DEFAULT 0,start_time text, stop_time text,start_timestamp integer, stop_timestamp integer,description text);
CREATE TABLE IF NOT EXISTS policies_schedules (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_id INTEGER,schedule_id INTEGER);
CREATE TABLE IF NOT EXISTS interface_settings (id INTEGER PRIMARY KEY AUTOINCREMENT,mode TEXT,name text, lan_interface text,lan_desc text,lan_queue INTEGER,wan_interface text,wan_desc text,wan_queue INTEGER, queue INTEGER , description text,cpu_index INTEGER ,manage_port INTEGER,create_date NUMERIC,tags TEXT);
CREATE TABLE IF NOT EXISTS sensei_version(id INTEGER PRIMARY KEY AUTOINCREMENT,version text,creation_date NUMERIC);
CREATE TABLE IF NOT EXISTS sensei_db_version(id INTEGER PRIMARY KEY AUTOINCREMENT,version text,creation_date NUMERIC);
CREATE TABLE IF NOT EXISTS policies_networks (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_id INTEGER,type INTEGER,network TEXT,desc TEXT,status INTEGER);
CREATE TABLE IF NOT EXISTS policies_macaddresses (id INTEGER PRIMARY KEY AUTOINCREMENT,policy_id INTEGER,type INTEGER,macaddresses TEXT,desc TEXT,status INTEGER);
CREATE TABLE IF NOT EXISTS shun_networks (id INTEGER PRIMARY KEY AUTOINCREMENT,type INTEGER,network TEXT,desc TEXT,status INTEGER);
CREATE TABLE IF NOT EXISTS user_configuration (id INTEGER PRIMARY KEY AUTOINCREMENT,user TEXT, key TEXT,value TEXT);
CREATE TABLE IF NOT EXISTS user_notices (id INTEGER PRIMARY KEY AUTOINCREMENT,notice_name TEXT, notice TEXT,type TEXT,status INTEGER  DEFAULT 0,create_date NUMERIC);
CREATE TABLE IF NOT EXISTS report_configuration(id INTEGER PRIMARY KEY AUTOINCREMENT,user TEXT, key TEXT,value TEXT);
CREATE TABLE IF NOT EXISTS restapi_keys (id INTEGER PRIMARY KEY AUTOINCREMENT,user TEXT NOT NULL,apikey TEXT,creation_time INTEGER NOT NULL DEFAULT 0,expire_time INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS users_cache (policyid INTEGER,sessionid	TEXT,authenticated_via TEXT,username TEXT,groups TEXT,ip_address TEXT,mac_address TEXT,hostname INTEGER NOT NULL DEFAULT 0,created	NUMBER,deleted INTEGER NOT NULL DEFAULT 0,logonid TEXT,action TEXT);
CREATE INDEX IF NOT EXISTS user_configuration_key_idx on user_configuration(key);
CREATE INDEX IF NOT EXISTS policy_web_categories_idx on policy_web_categories(policy_id);
CREATE INDEX IF NOT EXISTS policy_app_categories_idx  on policy_app_categories(policy_id);
CREATE INDEX IF NOT EXISTS policy_custom_web_categories_idx  on policy_custom_web_categories(policy_id);
CREATE INDEX IF NOT EXISTS policies_networks_idx on policies_networks(policy_id);
CREATE INDEX IF NOT EXISTS policy_app_categories_uuid_idx on policy_app_categories(uuid);
CREATE INDEX IF NOT EXISTS policy_web_categories_uuid_idx on policy_web_categories(uuid);
CREATE INDEX IF NOT EXISTS restapi_key_index ON restapi_keys(user);
CREATE UNIQUE INDEX IF NOT EXISTS applications_unique_idx on applications(name,web_20_category_id,application_category_id);
CREATE UNIQUE INDEX IF NOT EXISTS custom_applications_unique_idx on custom_applications(name);
CREATE UNIQUE INDEX IF NOT EXISTS custom_applications_host_idx on custom_applications_host_ip(host);
CREATE UNIQUE INDEX IF NOT EXISTS custom_applications_ip_idx on custom_applications_host_ip(ip);
CREATE UNIQUE INDEX IF NOT EXISTS policy_custom_app_categories_unique_idx on policy_custom_app_categories(policy_id,custom_application_id);
INSERT INTO sensei_version(version,creation_date) select '1.12',strftime('%s', 'now')  where (select count(*) from sensei_version where version='1.12') = 0;
INSERT INTO policies(id,uuid,name,usernames,groups,status,cloud_id) select 0,'0','Default','system','system',1,'' where not exists(select 1 from policies where id=0);
UPDATE custom_web_categories set name=trim(name);
DELETE FROM user_notices where notice_name='Upgrade_to_premium';
DELETE FROM user_notices where notice_name='Upgrade_to_portal';
DELETE FROM user_notices where notice_name='Upgrade_to_premium_partner';
insert into user_notices(notice_name,notice) values('Upgrade_to_premium','<p>Start your free 15-day <a data-toggle="modal" data-target="#license-trial">Business Subscription Trial now!</a></p>');
insert into user_notices(notice_name,notice) values('Upgrade_to_premium_partner','<p>Exclusive to __partner_name__ customers: Enjoy a 30-day Free Trial of Zenarmor Business Subscription! <a data-toggle="modal" data-target="#license-trial">“Click here”</a> to claim your free activation key!</p>');
insert into user_notices(notice_name,notice) values('Upgrade_to_portal','<p>You can now manage all your Zenarmor nodes through the Cloud Management Console. Click <a target="_self" href="/ui/sensei/#/configuration/cloudManagement">“here”</a> to get started! Click on <a data-toggle="modal" target="_blank" href="https://sunnyvalley.cloud/?utm_source=webui-opnsense-my-account&utm_medium=webui">“My Account”</a> to access your account.</p>');
update custom_web_categories set name='Whitelisted' where name='Auto Whitelist Hosts';
update custom_web_categories set name='Blacklisted' where name='Auto Blocklist Hosts';
CREATE UNIQUE INDEX IF NOT EXISTS custom_web_category_sites_unique_idx on custom_web_category_sites(custom_web_categories_id,site);